### ISSUE TITLE
Dashboard not found

### ISSUE THREAD

**Issue by ugintl** [getspooky/yaldash#75] opened 2022-01-23 16:45 UTC
After installation, when I go to mysite.com/dashboard it says "Not Found". I am on laravel 8

**Comment by oliuz** [comment] 2022-01-24 19:13
Hi @ugintl 

This issue is resolved with the PR #76

**Comment by ugintl** [comment] 2022-01-25 02:53
But is have not been merged I think. How I should apply it to the yaldash repo I have on my computer? `git pull`?

**Comment by oliuz** [comment] 2022-01-26 12:04
Hi @ugintl 

The new package update has already been published, the issue is closed.

**Closed as completed by oliuz** 2022-01-26 12:04 UTC
